// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORMDemoUsingEFCore;

namespace ORMDemoUsingEFCore.Migrations
{
    [DbContext(typeof(CardManagementContext))]
    [Migration("20210728113955_InitialDatabaseCreate")]
    partial class InitialDatabaseCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("ORMDemoUsingEFCore.Models.CreditCard", b =>
                {
                    b.Property<int>("CreditCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CVV")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardHoldeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpireDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CreditCardId");

                    b.ToTable("CreditCards");
                });
#pragma warning restore 612, 618
        }
    }
}
